package:
  name: dlib
  version: "18.16"

source:
  fn: dlib-18.16.tar.bz2
  url: http://sourceforge.net/projects/dclib/files/dlib/v18.16/dlib-18.16.tar.bz2/download
  sha1: 6b4944ea3638e896016f3cbb286da9c1faa4d588

build:
  features:
    - mkl

  string: "py{{ environ['PY_VER']|replace('.', '') }}_mkl_0"

requirements:
  build:
   - python
   - mkl-rt
   - cmake  # [win]
   - boost 1.56.0
   - sqlite 3.8.4.1  # [unix]

  run:
   - python
   - mkl-rt
   - boost 1.56.0
   - sqlite 3.8.4.1  # [unix]

test:
  requires:
    - scipy

  imports:
    - dlib

about:
  home: http://dlib.net/
  license: Boost Software License
